project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "*.Rmd"
    - "!x5-rmarkdown-intro.Rmd"

website:
  title: "Elements of Data Analysis and Statistics"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: Basic Statistics
        contents:
          - 01-introduction.qmd
          - 02-terminology.qmd
          - 03-statparams.qmd
          - 04-distributions.qmd
          - 05-classtests.qmd
          - 06-linear.qmd
          - 07-anova.qmd
          - 08-nonlinear-regression.qmd
          - 09-timeseries-basics.qmd
      - section: Tutorials
        contents:
          - s1-introductory-r-session.Rmd
          - s2-multivar-3d.Rmd
          - s3-multivar-lakes.Rmd
      - section: R Topics
        contents:
          - x1-r-basics.qmd
          - x2-r-graphics.qmd
          - x3-r-functions.qmd
          - x4-pipes-intro.qmd

#format:
#  html:
#    theme: cosmo
#    css: colors.css
#    toc: true
    
author: "Thomas Petzoldt"
date-format: "YYYY-MM-DD"
title-slide-attributes:
  data-background-image: "img/tud-title-bg-wide-2021.png"
  body-color: "#069af22"
#  data-background-opacity: "0.5"
include-in-header:
  - text: |
      <style>
      #title-slide 
        .title {color: #ee7f00;}
        .subtitle {color: #ee7f00;}
        .quarto-title-author {color: #69af22;}
        .date {color: #69af22;}
      </style>  
format: 
  revealjs:
    theme: [sky, thpe-large-white.scss]
    css: colors.css
    transition: fade
    data-transition-speed: fast
    navigation-mode: linear     
bibliography: bib.bib
csl: apa




